// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: followers.sql

package db

import (
	"context"
)

const followUser = `-- name: FollowUser :exec
INSERT INTO followers (user_id, follower_id)
VALUES ($1, $2)
`

type FollowUserParams struct {
	UserID     int64 `json:"user_id"`
	FollowerID int64 `json:"follower_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.UserID, arg.FollowerID)
	return err
}

const unFollowUser = `-- name: UnFollowUser :exec
DELETE FROM followers
WHERE user_id = $1 AND follower_id = $2
`

type UnFollowUserParams struct {
	UserID     int64 `json:"user_id"`
	FollowerID int64 `json:"follower_id"`
}

func (q *Queries) UnFollowUser(ctx context.Context, arg UnFollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unFollowUser, arg.UserID, arg.FollowerID)
	return err
}
