// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: role.sql

package db

import (
	"context"
)

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, level, description
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, level, description
FROM roles
WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
	)
	return i, err
}
